### ISSUE TITLE
GG my friend

### ISSUE THREAD

**Issue by Zewodec** [Zewodec/Electronic-Journal-of-the-Computer-Laboratory#1]
Давайте скажемо "_GG_" для нашого дорогого одногрупника...

**Comment by Zewodec** [comment]
GG

**Comment by KuzoOleh** [comment]
GG

**Comment by Zewodec** [comment]
Дякую за співпрацю. До нових проектів)

@Mementora Закриєш своїм коментом цей issue

**Comment by KuzoOleh** [comment]
@Zewodec йопта, взаємно. Я вже потім закрию цю проблему, бо в нас зараз проблема з війною, а точніше проблема з русойобусам, які сюда зайшли

**Comment by Zewodec** [comment]
@Mementora Тд це дійсно проблема... Треба воювати! Все буде Україна!
🟦🟦🟦🟦
🟨🟨🟨🟨
