### ISSUE TITLE
Check if authorized user is admin

### ISSUE THREAD

**Issue by KuzoOleh** [Zewodec/Electronic-Journal-of-the-Computer-Laboratory#10]
- [x] if user is admin, show admin's buttons
- [x] if user is not admin, hide admin's buttons

**Comment by KuzoOleh** [comment]
поки що проблема полягає в тому, щоб сховати кнопки, якщо юзер не адмін

**Comment by Zewodec** [comment]
@Mementora Зроби їх по стандарту не видимими, а потім лиш в коді, якщо юзер адмін, то показувати

**Comment by KuzoOleh** [comment]
Ок, я зробив цю перевірку, і поки вона працює, але я так подумав, що треба зробити ще одне вікно - меню, де можна буде подивитися на юзерів, подивитись на журнал і змінити аккаунт

**Comment by Zewodec** [comment]
@Mementora Можна зробити
