### ISSUE TITLE
Записи

### ISSUE THREAD

**Issue by KuzoOleh** [Zewodec/Electronic-Journal-of-the-Computer-Laboratory#12]
Часу в нас небагато залишилось, тому треба відобразити записи з бд в таблицю, дописати пару кнопок, ще щось зробити і все ок, тому:

- [x] відобразити записи в таблицю
- [x] дописати кнопки
- [x] добавити записи
- [x] добавити можливість додавання записів

**Comment by Zewodec** [comment]
@Mementora За*бало😅

**Comment by KuzoOleh** [comment]
Ти сам вирішив брати цю роботу)

**Comment by KuzoOleh** [comment]
`        public void Update_table() throws SQLException{
        try{
        String sql = "SELECT * FROM STUDENT";
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            student_name.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex){
        Logger.getLogger(JavaApplication1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }`

**Comment by Zewodec** [comment]
[rs2xml.zip](https://github.com/Zewodec/Electronic-Journal-of-the-Computer-Laboratory/files/8072940/rs2xml.zip)

**Comment by KuzoOleh** [comment]
До речі, треба трохи розібратися, як саме працює changeSelection, і добавити його на всі кнопки. А основне - це зрозуміти, як це зробити так, щоб можна було б нормально переключатися між записами, бо воно якось дивно працює

**Comment by Zewodec** [comment]
yess
