### ISSUE TITLE
БД

### ISSUE THREAD

**Issue by Zewodec** [Zewodec/Electronic-Journal-of-the-Computer-Laboratory#2]
- [x] Таблиця користувачів
  - [x] id
  - [x] username
  - [x] password
  - [x] role (user, admin)
  - [x] last_login_in

- [x] Таблиця журналу
  - [x] id
  - [x] item_num
  - [x] description
  - [x] date_add
  - [x] date_last_update

**Comment by KuzoOleh** [comment]
Яким типом має бути last_login_in?

**Comment by Zewodec** [comment]
Дата/час
Вроді TimeStamp, але чекни

вт, 8 лют. 2022, 15:04 користувач Oleh Kuzo ***@***.***> пише:

**Comment by KuzoOleh** [comment]
`INSERT INTO ROOT."Users"(ROOT."Users"."Id",ROOT."Users"."Username", ROOT."Users"."Password",ROOT."Users"."IsAdmin",ROOT."Users"."Last_Login")
VALUES(2, 'Olegkuzo', 'qwerty',false, CURRENT_TIMESTAMP);`
